package com.xtjnoob.bean;

import org.springframework.stereotype.Component;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrty_password
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    private String encrtyPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrty_password
     *
     * @return the value of user_password.encrty_password
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    public String getEncrtyPassword() {
        return encrtyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrty_password
     *
     * @param encrtyPassword the value for user_password.encrty_password
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    public void setEncrtyPassword(String encrtyPassword) {
        this.encrtyPassword = encrtyPassword == null ? null : encrtyPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Sun May 05 10:55:56 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}