server:
  port: 8081

spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver